baseURL = 'https://novumworld.com/' # Despliegue automático vercel
languageCode = 'es-es'
title = 'NovumWorld - Oficial'
theme = 'ananke'
buildFuture = true
[pagination]
  pagerSize = 50

relativeURLs = true
canonifyURLs = true

[[menu.main]]
  identifier = "about"
  name = "Sobre Nosotros"
  url = "/about/"
  weight = 10
[[menu.main]]
  identifier = "privacy"
  name = "Privacidad"
  url = "/privacy/"
  weight = 20
[[menu.main]]
  identifier = "contact"
  name = "Contacto"
  url = "/contact/"
  weight = 30
