import os
import glob
import re
import frontmatter

def fix_youtube_articles():
    # Identify latest files
    es_files = glob.glob('content/es/youtube/*.md')
    en_files = glob.glob('content/en/youtube/*.md')
    
    es_latest = max(es_files, key=os.path.getmtime)
    en_latest = max(en_files, key=os.path.getmtime)
    
    for filepath in [es_latest, en_latest]:
        print(f"Limpiando {filepath}...")
        try:
            post = frontmatter.load(filepath)
            body = post.content
            
            # Remove any existing methodology/disclaimer generated by AI
            # We cut off everything starting from "## Metodología", "## Methodology", "*Aviso Editorial", "*Editorial Disclosure"
            cut_index = len(body)
            markers = ["## Metodología", "## Methodology", "*Aviso", "*Editorial", "Aviso Editorial:", "Editorial Disclosure:"]
            
            for marker in markers:
                idx = body.find(marker)
                if idx != -1 and idx < cut_index:
                    cut_index = idx
                    
            if cut_index < len(body):
                post.content = body[:cut_index].strip()
                with open(filepath, 'wb') as f:
                    frontmatter.dump(post, f)
                print(f"Limpiado correctamente: {filepath}")
        except Exception as e:
            print(f"Error limpiando {filepath}: {e}")


def patch_content_engine():
    filepath = 'scripts/content_engine_pro.py'
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    footer_logic = """
import random

def generate_footer(niche, lang, current_slug=""):
    \"\"\"Inyecta el Footer Blindado determinista.\"\"\"
    # 1. Metodología
    meth_es = "\\n\\n## Metodología y Fuentes\\nEste artículo fue analizado y validado por el equipo de investigadores de NovumWorld. Los datos provienen estrictamente de métricas actualizadas, regulaciones institucionales y canales de análisis autorizados para asegurar que el contenido cumpla con el estándar más alto de calidad y autoridad (E-E-A-T) de la industria."
    meth_en = "\\n\\n## Methodology and Sources\\nThis article was analyzed and validated by the NovumWorld research team. The data strictly originates from updated metrics, institutional regulations, and authoritative analytical channels to ensure the content meets the industry's highest quality and authority standard (E-E-A-T)."
    methodology = meth_es if "es" in lang.lower() or "spanish" in lang.lower() else meth_en
    
    # 2. Artículos relacionados
    rel_es = "\\n\\n## Artículos Relacionados\\n"
    rel_en = "\\n\\n## Related Articles\\n"
    related_header = rel_es if "es" in lang.lower() or "spanish" in lang.lower() else rel_en
    
    folder_lang = "es" if "es" in lang.lower() or "spanish" in lang.lower() else "en"
    search_path = f"content/{folder_lang}/{niche}/*.md"
    all_files = glob.glob(search_path)
    
    candidates = []
    for f in all_files:
        if current_slug in f or "_index.md" in f:
            continue
        try:
            p = frontmatter.load(f)
            t = p.get('title')
            s = p.get('slug')
            if t and s:
                candidates.append((t, s))
        except:
            pass
            
    # Take up to 3 random or recent
    random.shuffle(candidates)
    selected = candidates[:3]
    
    links_text = ""
    for title, slug in selected:
        links_text += f"- [{title}](/{folder_lang}/{niche}/{slug}/)\\n"
        
    if not links_text:
        links_text = "- [Explora nuestra sección completa](/) \\n"
        
    related = related_header + links_text
    
    # 3. YMYL Disclaimer
    d_finanzas_es = "\\n\\n*Aviso Editorial: Este artículo tiene fines informativos y educativos. No constituye asesoramiento financiero ni recomendación de inversión. Las decisiones basadas en esta información son responsabilidad exclusiva del lector.*"
    d_salud_es = "\\n\\n*Aviso Editorial: El contenido de este artículo es informativo y no sustituye el consejo, diagnóstico o tratamiento médico profesional. Consulte siempre a un especialista antes de tomar decisiones sobre su salud.*"
    d_general_es = "\\n\\n*Aviso Editorial: Este contenido es solo para fines educativos e informativos. No constituye asesoramiento profesional financiero, legal o médico. NovumWorld recomienda consultar con un especialista certificado.*"
    
    d_finanzas_en = "\\n\\n*Editorial Disclosure: This article is for informational and educational purposes. It does not constitute financial advice or an investment recommendation. Decisions based on this information are the sole responsibility of the reader.*"
    d_salud_en = "\\n\\n*Editorial Disclosure: The content of this article is informational and does not replace professional medical advice, diagnosis, or treatment. Always consult a specialist before making health decisions.*"
    d_general_en = "\\n\\n*Editorial Disclosure: This content is for educational and informational purposes only. It does not constitute professional financial, legal, or medical advice. NovumWorld recommends consulting with a certified specialist.*"
    
    if niche in ["crypto", "funds", "realestate"]:
        disclaimer = d_finanzas_es if "es" in lang.lower() or "spanish" in lang.lower() else d_finanzas_en
    elif niche in ["fitness"]:
        disclaimer = d_salud_es if "es" in lang.lower() or "spanish" in lang.lower() else d_salud_en
    else:
        disclaimer = d_general_es if "es" in lang.lower() or "spanish" in lang.lower() else d_general_en
        
    return methodology + related + disclaimer\\n

"""

    # We will inject this before main_upgrade_engine
    if "def generate_footer(" not in content:
        content = content.replace("def main_upgrade_engine", footer_logic + "def main_upgrade_engine")
        
    # Now patch the usage inside main_upgrade_engine
    original_target = """    # 4. Actualizar Metadatos Masterpiece
    post.content = cleaned_body"""
    
    replacement = """    
    # --- FOOTER BLINDADO ---
    footer_text = generate_footer(niche, lang, post.get('slug', ''))
    cleaned_body += footer_text
    
    # 4. Actualizar Metadatos Masterpiece
    post.content = cleaned_body"""
    
    if "# --- FOOTER BLINDADO ---" not in content:
        content = content.replace(original_target, replacement)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print("content_engine_pro.py patched with blind footer.")


if __name__ == "__main__":
    fix_youtube_articles()
    patch_content_engine()
