name: Notificar a Vercel
on:
  push:
    branches:
      - main
    paths:
      - 'content/**'
      - 'layouts/**'
      - 'themes/**'
      - 'static/**'
      - 'config**'
      - 'hugo.**'
      - 'assets/**'

jobs:
  notify-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_LjlrJDxuqvOkEGHe0Co0lUtbRWLe/52jxi0PIPf"
